name: main
on: push
env:
  PYTHON_VERSION: 3.9
  AWS_DEFAULT_REGION: 'us-east-1'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  test-app:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - name: install boto3
        run: pip install boto3
      - name: Unit Testing
        run: cd tests && cd integration & python test_api_gateway.py && cd .. && cd ..

  deploy-infra:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: '3.9'
            architecture: 'x64'
        - uses: aws-actions/setup-sam@v1
        - uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
        - run: sam build
        - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset

    
